### ISSUE TITLE
Fuzz: Spurious failure in fd_set_merge

### ISSUE THREAD

**Issue by darconeous** [openthread/wpantund#226]
While running the new fuzzer, I noticed that occasionally we will get a spurious failure that doesn't reproduce when run again with the same input. It always seems to have the same backtrace:

```
==12==ERROR: AddressSanitizer: global-buffer-overflow on address 0x000001908b00 at pc 0x00000068aa2c bp 0x7ffe3fbe7020 sp 0x7ffe3fbe7018
READ of size 4 at 0x000001908b00 thread T0
    #0 0x68aa2b in fd_set_merge /src/src/wpantund/../util/nlpt-select.c:44:16
    #1 0x68aa2b in nlpt_select_update_fd_set /src/src/wpantund/../util/nlpt-select.c:61
    #2 0x64ceb8 in nl::wpantund::NCPInstanceBase::update_fd_set(fd_set*, fd_set*, fd_set*, int*, int*) /src/src/wpantund/NCPInstanceBase-AsyncIO.cpp:182:3
    #3 0x503d6c in MainLoop::block_until_ready() /src/src/wpantund/./wpantund.cpp:560:3
    #4 0x4fceb0 in NCPInputFuzzTarget(unsigned char const*, unsigned long) /src/src/wpantund/wpantund-fuzz.cpp:109:26
    #5 0x4ffac0 in LLVMFuzzerTestOneInput /src/src/wpantund/wpantund-fuzz.cpp:224:11
...
```

It's not immediately obvious what might be causing this, but it is worth looking into. This failure can be easily reproduced using the [fuzzing instructions](https://github.com/openthread/wpantund/wiki/Fuzzing) after applying the changes from #224.

**Comment by darconeous** [comment]
I don't seem to see this issue crop up any more. Closing for now.
