### ISSUE TITLE
Fuzz: failures

### ISSUE THREAD

**Issue by abtink** [openthread/wpantund#406]
We got 4 `oss-fuzz` errors. They all seem to be around this: https://github.com/openthread/wpantund/blob/20d63e05a7c1265df93413e754d9eab288bab692/src/ncp-spinel/SpinelNCPInstance.cpp#L4211

```

==1==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f6137400c76 bp 0x7ffe8ed39e60 sp 0x7ffe8ed39618 T0)
--
  | ==1==The signal is caused by a READ memory access.
  | ==1==Hint: address points to the zero page.
  | SCARINESS: 10 (null-deref)
  | #0 0x7f6137400c75 in memcpy-avx-unaligned.S:237 /build/glibc-Cl5G7W/glibc-2.23/sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:237
  | #1 0x52efe7 in __asan_memcpy _asan_rtl_:3
  | #2 0x5b7ce0 in std::__1::enable_if<((is_trivially_move_constructible<unsigned char>::value) && (is_same<unsigned char, unsigned char>::value)) && ((std::__1::integral_constant<bool, true>::value) \|\| (!(__has_construct<std::__1::allocator<unsigned char>, unsigned char*, bool&>::value))), void>::type std::__1::allocator_traits<std::__1::allocator<unsigned char> >::__construct_range_forward<unsigned char const, unsigned char, unsigned char, unsigned char>(std::__1::allocator<unsigned char>&, bool*, bool*, unsigned char*&) /usr/local/include/c++/v1/memory:1666:17
  | #3 0x5b7346 in std::__1::enable_if<__is_forward_iterator<unsigned char const*>::value, void>::type std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >::__construct_at_end<unsigned char const*>(unsigned char const*, unsigned char const*, unsigned long) /usr/local/include/c++/v1/vector:1069:5
  | #4 0x5b6f9a in std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >::vector<unsigned char const*>(unsigned char const*, std::__1::enable_if<(__is_forward_iterator<unsigned char const*>::value) && (is_constructible<unsigned char, std::__1::iterator_traits<unsigned char const*>::reference>::value), unsigned char const*>::type) /usr/local/include/c++/v1/vector:1217:9
  | #5 0x6d6d94 in nl::wpantund::SpinelNCPInstance::handle_ncp_spinel_value_is_SERVICES(unsigned char const*, unsigned int) wpantund/src/ncp-spinel/SpinelNCPInstance.cpp:4212:8
  | #6 0x6db3e8 in nl::wpantund::SpinelNCPInstance::handle_ncp_spinel_value_is(spinel_prop_key_t, unsigned char const*, unsigned int) wpantund/src/ncp-spinel/SpinelNCPInstance.cpp:4729:3
  | #7 0x6e2880 in nl::wpantund::SpinelNCPInstance::handle_ncp_spinel_callback(unsigned int, unsigned char const*, unsigned int) wpantund/src/ncp-spinel/SpinelNCPInstance.cpp:5247:5
  | #8 0x70c9a1 in nl::wpantund::SpinelNCPInstance::ncp_to_driver_pump() wpantund/src/ncp-spinel/SpinelNCPInstance-DataPump.cpp:333:4
  | #9 0x66a755 in nl::wpantund::NCPInstanceBase::process() wpantund/src/wpantund/NCPInstanceBase-AsyncIO.cpp:244:3
  | #10 0x6e5ed2 in nl::wpantund::SpinelNCPInstance::process() wpantund/src/ncp-spinel/SpinelNCPInstance.cpp:5760:19
  | #11 0x566e7a in MainLoop::process() wpantund/src/wpantund/wpantund.cpp:549:17
```
```

INFO: Loaded 1 PC tables (33379 PCs): 33379 [0x72dd60,0x7b0390),
--
  | /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_wpantund_a601ffc740aacb896034999f8a3c0ad31821b166/revisions/wpantund-fuzz: Running 1 inputs 100 time(s) each.
  | Running: /fuzz-1
  | UndefinedBehaviorSanitizer:DEADLYSIGNAL
  | ==1==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x00006a2d4f97 (pc 0x7f06757b9168 bp 0x7ffc69df81e0 sp 0x7ffc69df81b8 T1)
  | ==1==The signal is caused by a READ memory access.
  | #0 0x7f06757b9167 in memcpy-avx-unaligned.S:244 /build/glibc-Cl5G7W/glibc-2.23/sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:244
  | #1 0x5023c8 in std::__1::enable_if<((is_trivially_move_constructible<unsigned char>::value) && (is_same<unsigned char, unsigned char>::value)) && ((std::__1::integral_constant<bool, true>::value) \|\| (!(__has_construct<std::__1::allocator<unsigned char>, unsigned char*, bool&>::value))), void>::type std::__1::allocator_traits<std::__1::allocator<unsigned char> >::__construct_range_forward<unsigned char const, unsigned char, unsigned char, unsigned char>(std::__1::allocator<unsigned char>&, bool*, bool*, unsigned char*&) /usr/local/include/c++/v1/memory:1666:17
  | #2 0x501d30 in std::__1::enable_if<__is_forward_iterator<unsigned char const*>::value, void>::type std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >::__construct_at_end<unsigned char const*>(unsigned char const*, unsigned char const*, unsigned long) /usr/local/include/c++/v1/vector:1069:5
  | #3 0x501b5a in std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >::vector<unsigned char const*>(unsigned char const*, std::__1::enable_if<(__is_forward_iterator<unsigned char const*>::value) && (is_constructible<unsigned char, std::__1::iterator_traits<unsigned char const*>::reference>::value), unsigned char const*>::type) /usr/local/include/c++/v1/vector:1217:9
  | #4 0x5c9851 in nl::wpantund::SpinelNCPInstance::handle_ncp_spinel_value_is_SERVICES(unsigned char const*, unsigned int) wpantund/src/ncp-spinel/SpinelNCPInstance.cpp:4211:8
  | #5 0x5cf20d in nl::wpantund::SpinelNCPInstance::handle_ncp_spinel_value_is(spinel_prop_key_t, unsigned char const*, unsigned int) wpantund/src/ncp-spinel/SpinelNCPInstance.cpp:4729:3
  | #6 0x5d487b in nl::wpantund::SpinelNCPInstance::handle_ncp_spinel_callback(unsigned int, unsigned char const*, unsigned int) wpantund/src/ncp-spinel/SpinelNCPInstance.cpp:5247:5
  | #7 0x5ee5d0 in nl::wpantund::SpinelNCPInstance::ncp_to_driver_pump() wpantund/src/ncp-spinel/SpinelNCPInstance-DataPump.cpp:333:4
  | #8 0x577610 in nl::wpantund::NCPInstanceBase::process() wpantund/src/wpantund/NCPInstanceBase-AsyncIO.cpp:244:3
  | #9 0x5d6908 in nl::wpantund::SpinelNCPInstance::process() wpantund/src/ncp-spinel/SpinelNCPInstance.cpp:5760:19
  | #10 0x4c5bd3 in MainLoop::process() wpantund/src/wpantund/wpantund.cpp:549:17

```
```

Running command: /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_wpantund_4653f817daf7286b83c846d053d557e57783edfc/revisions/wpantund-fuzz -timeout=5 -rss_limit_mb=2048 -runs=100 /fuzz-0
--
  | INFO: Seed: 3294449638
  | INFO: Loaded 1 modules   (24237 inline 8-bit counters): 24237 [0xb75448, 0xb7b2f5),
  | INFO: Loaded 1 PC tables (24237 PCs): 24237 [0x81d318,0x87bde8),
  | /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_wpantund_4653f817daf7286b83c846d053d557e57783edfc/revisions/wpantund-fuzz: Running 1 inputs 100 time(s) each.
  | Running: /fuzz-0
  | =================================================================
  | ==1==AddressSanitizer CHECK failed: /src/llvm/projects/compiler-rt/lib/asan/asan_descriptions.cc:80 "((0 && "Address is not in memory and not in shadow?")) != (0)" (0x0, 0x0)
  | #0 0x5377ee in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) _asan_rtl_:5
  | #1 0x54bb6f in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /src/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_termination.cc:78:5
  | #2 0x4c02ad in GetShadowKind _asan_rtl_
  | #3 0x4c02ad in __asan::GetShadowAddressInformation(unsigned long, __asan::ShadowAddressDescription*) _asan_rtl_
  | #4 0x4c1336 in __asan::AddressDescription::AddressDescription(unsigned long, unsigned long, bool) _asan_rtl_:7
  | #5 0x4c2e52 in __asan::ErrorGeneric::ErrorGeneric(unsigned int, unsigned long, unsigned long, unsigned long, unsigned long, bool, unsigned long) _asan_rtl_:7
  | #6 0x5351ef in __asan::ReportGenericError(unsigned long, unsigned long, unsigned long, unsigned long, bool, unsigned long, unsigned int, bool) _asan_rtl_:16
  | #7 0x52ef18 in __asan_memcpy _asan_rtl_:3
  | #8 0x5b7ce0 in std::__1::enable_if<((is_trivially_move_constructible<unsigned char>::value) && (is_same<unsigned char, unsigned char>::value)) && ((std::__1::integral_constant<bool, true>::value) \|\| (!(__has_construct<std::__1::allocator<unsigned char>, unsigned char*, bool&>::value))), void>::type std::__1::allocator_traits<std::__1::allocator<unsigned char> >::__construct_range_forward<unsigned char const, unsigned char, unsigned char, unsigned char>(std::__1::allocator<unsigned char>&, bool*, bool*, unsigned char*&) /usr/local/include/c++/v1/memory:1666:17
  | #9 0x5b7346 in std::__1::enable_if<__is_forward_iterator<unsigned char const*>::value, void>::type std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >::__construct_at_end<unsigned char const*>(unsigned char const*, unsigned char const*, unsigned long) /usr/local/include/c++/v1/vector:1069:5
  | #10 0x5b6f9a in std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >::vector<unsigned char const*>(unsigned char const*, std::__1::enable_if<(__is_forward_iterator<unsigned char const*>::value) && (is_constructible<unsigned char, std::__1::iterator_traits<unsigned char const*>::reference>::value), unsigned char const*>::type) /usr/local/include/c++/v1/vector:1217:9
  | #11 0x6d6d42 in nl::wpantund::SpinelNCPInstance::handle_ncp_spinel_value_is_SERVICES(unsigned char const*, unsigned int) wpantund/src/ncp-spinel/SpinelNCPInstance.cpp:4211:8
  | #12 0x6db3e8 in nl::wpantund::SpinelNCPInstance::handle_ncp_spinel_value_is(spinel_prop_key_t, unsigned char const*, unsigned int) wpantund/src/ncp-spinel/SpinelNCPInstance.cpp:4729:3
  | #13 0x6e2880 in nl::wpantund::SpinelNCPInstance::handle_ncp_spinel_callback(unsigned int, unsigned char const*, unsigned int) wpantund/src/ncp-spinel/SpinelNCPInstance.cpp:5247:5
  | #14 0x70c9a1 in nl::wpantund::SpinelNCPInstance::ncp_to_driver_pump() wpantund/src/ncp-spinel/SpinelNCPInstance-DataPump.cpp:333:4
  | #15 0x66a755 in nl::wpantund::NCPInstanceBase::process() wpantund/src/wpantund/NCPInstanceBase-AsyncIO.cpp:244:3
  | #16 0x6e5ed2 in nl::wpantund::SpinelNCPInstance::process() wpantund/src/ncp-spinel/SpinelNCPInstance.cpp:5760:19
  | #17 0x566e7a in MainLoop::process() wpantund/src/wpantund/wpantund.cpp:549:17
  | #18 0x565a53 in NCPInputFuzzTarget(unsigned char const*, unsigned long) wpantund/src/wpantund/wpantund-fuzz.cpp:199:13
  | #19 0x5674e6 in LLVMFuzzerTestOneInput wpantund/src/wpantund/wpantund-fuzz.cpp:275:10
  | #20 0x46a1d4 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:529:15
  | #21 0x46af85 in fuzzer::Fuzzer::TryDetectingAMemoryLeak(unsigned char const*, unsigned long, bool) /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:605:3
  | #22 0x4583e9 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:287:6
  | #23 0x45d17b in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:715:9
  | #24 0x4839d2 in main /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerMain.cpp:19:10
  | #25 0x7f5718c6982f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/libc-start.c:291
  | #26 0x41e9f8 in _start

```

**Comment by abtink** [comment]
Submitted https://github.com/openthread/wpantund/pull/407
Seems to have addresses the above issues.
