### ISSUE TITLE
oss-fuzz issue 

### ISSUE THREAD

**Issue by abtink** [openthread/wpantund#408]
One more fuzz-oss error:

```

Running command: /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_wpantund_a601ffc740aacb896034999f8a3c0ad31821b166/revisions/wpantund-fuzz -timeout=5 -rss_limit_mb=2048 -runs=100 /fuzz-3
--
  | INFO: Seed: 894465601
  | INFO: Loaded 1 modules   (33386 inline 8-bit counters): 33386 [0xab1040, 0xab92aa),
  | INFO: Loaded 1 PC tables (33386 PCs): 33386 [0x731710,0x7b3db0),
  | /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_wpantund_a601ffc740aacb896034999f8a3c0ad31821b166/revisions/wpantund-fuzz: Running 1 inputs 100 time(s) each.
  | Running: /fuzz-3
  | SpinelNCPInstance.cpp:4209:37: runtime error: load of value 195, which is not a valid value for type 'bool'
  | #0 0x5cd429 in nl::wpantund::SpinelNCPInstance::handle_ncp_spinel_value_is_SERVICES(unsigned char const*, unsigned int) wpantund/src/ncp-spinel/SpinelNCPInstance.cpp:4209:37
  | #1 0x5d284a in nl::wpantund::SpinelNCPInstance::handle_ncp_spinel_value_is(spinel_prop_key_t, unsigned char const*, unsigned int) wpantund/src/ncp-spinel/SpinelNCPInstance.cpp:4729:3
  | #2 0x5d7f1b in nl::wpantund::SpinelNCPInstance::handle_ncp_spinel_callback(unsigned int, unsigned char const*, unsigned int) wpantund/src/ncp-spinel/SpinelNCPInstance.cpp:5247:5
  | #3 0x5f1889 in nl::wpantund::SpinelNCPInstance::ncp_to_driver_pump() wpantund/src/ncp-spinel/SpinelNCPInstance-DataPump.cpp:333:4
  | #4 0x57ab90 in nl::wpantund::NCPInstanceBase::process() wpantund/src/wpantund/NCPInstanceBase-AsyncIO.cpp:244:3
  | #5 0x5d9fa8 in nl::wpantund::SpinelNCPInstance::process() wpantund/src/ncp-spinel/SpinelNCPInstance.cpp:5760:19
  | #6 0x4c9233 in MainLoop::process() wpantund/src/wpantund/wpantund.cpp:549:17
  | #7 0x4c876e in NCPInputFuzzTarget(unsigned char const*, unsigned long) wpantund/src/wpantund/wpantund-fuzz.cpp:199:13
  | #8 0x4c9889 in LLVMFuzzerTestOneInput wpantund/src/wpantund/wpantund-fuzz.cpp:275:10
  | #9 0x455224 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:553:15

````

**Comment by abtink** [comment]
This is addressed by recent changes.
